# Generated by Django 2.1.3 on 2018-11-10 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isrc', models.CharField(max_length=200)),
                ('spotify_track_uri', models.CharField(max_length=200)),
                ('cover_art_url', models.TextField()),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('tempo', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('energy', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Genre')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Track')),
            ],
        ),
    ]
