# Generated by Django 2.1.3 on 2018-11-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackgenres',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='trackgenres',
            name='track',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='TrackGenres',
        ),
    ]
